SELECT C.HISTORY_ID, ROUND(C.DAILY_FEE * (100-IFNULL(D.DISCOUNT_RATE, 0)) / 100 * C.DURATION, 0) AS FEE
FROM (SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE, B.HISTORY_ID, DURATION,
        CASE
            WHEN DURATION >= 7 AND DURATION < 30
            THEN '7일 이상'
            WHEN DURATION >= 30 AND DURATION < 90
            THEN '30일 이상'
            WHEN DURATION >= 90
            THEN '90일 이상'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR AS A
        INNER JOIN (SELECT *, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS B
        ON A.CAR_ID = B.CAR_ID
    ) AS C
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
    ON C.CAR_TYPE = D.CAR_TYPE
        AND C.DURATION_TYPE = D.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, C.HISTORY_ID DESC