SELECT A.CAR_ID, IFNULL(B.AVAILABILITY, "대여 가능") AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
    LEFT JOIN (
        SELECT *, '대여중' AS AVAILABILITY
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE DATEDIFF('2022-10-16', start_date) >= 0
            AND DATEDIFF('2022-10-16', end_date) <= 0
    ) AS B
    ON A.CAR_ID = B.CAR_ID
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC